### PR TITLE
Migrate to dub build system

### PR DESCRIPTION
**Pull request by mathiascode**
Dub is the standard build system for D. It's easier to deal with than our Makefile, and provides various useful commands we can use in the future, such as 'dub test' for unit tests and 'dub lint' for linting.

### CODE REVIEW

**Comment by slook** [comment]
```
$ dub build --debug=db --debug=msg --debug=user
Performing "debug" build using /usr/bin/ldc2 for x86_64.
soulfind:soulfind ~dub: building configuration ""...
src/db.d(38,4): Warning: statement is not reachable
src/db.d(266,4): Warning: statement is not reachable
Error: warnings are treated as errors
       Use -wi if you wish to treat warnings only as informational.
/usr/bin/ldc2 failed with exit code 1.
$ 
$ dub build
Performing "debug" build using /usr/bin/ldc2 for x86_64.
soulfind:soulfind ~dub: building configuration ""...
src/db.d(38,4): Warning: statement is not reachable
src/db.d(266,4): Warning: statement is not reachable
Error: warnings are treated as errors
       Use -wi if you wish to treat warnings only as informational.
/usr/bin/ldc2 failed with exit code 1.
$ 
$ dub --version
DUB version 1.27.0-3, built on Aug 13 2022
```

**Comment by mathiascode** [comment]
I restructured the code in order to reuse `main.d` for both `soulfind` and `soulsetup`.

**Comment by slook** [comment]
Any encountered exception error message should be the last line displayed on the console, as before...

```
$ ./soulfind 
Unable to bind socket to port 2242
$ 
```

but after the restructuring now...
```
$ ./soulfind 
Unable to bind socket to port 2242

A la prochaine...
$ 
```

The exit greeting message should only be displayed if the program exited successfully with `0`.

**Comment by mathiascode** [comment]
I was a bit too greedy there. I've defined the exit message as a constant instead.

**Pull request merged**
